WDP221201-16 Fix for featureBoxes
odevpl/wdp-2212 pull request #28
Opened 2022-12-12 23:55 UTC by dave8git

2022-12-13 15:17 UTC, odevpl approved these changes

2022-12-13 15:21 UTC, odevpl requested changes

2022-12-14 14:31 UTC, Grzegonim requested changes
Elementy na mobilkach różnią się wysokością, sprawdzałem na przykładzie Iphone XR

2022-12-15 20:18 UTC, Grzegonim approved these changes

2022-12-15 20:19 UTC, Grzegonim approved these changes

2022-12-15 20:20 UTC, Grzegonim approved these changes

2022-12-15 20:20 UTC, Grzegonim approved these changes

2022-12-15 20:21 UTC, Grzegonim approved these changes

2022-12-15 20:30 UTC, odevpl approved these changes

2022-12-15 20:31 UTC, merged